# Generated by Django 4.0.4 on 2022-05-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
