# Generated by Django 4.0.4 on 2022-05-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviewer',
        ),
    ]
